pr Feat/28 join api
ttoklip/BackEnd pull request #134
Opened 2024-06-18 04:43 UTC by why-only-english

### Issue number and Link
이슈 번호
- #125 

### Summary
회원가입 및 인증 메일 전송, 검증 구현하였습니다.

### PR Type
- [ ] Feature
- [ ] Bugfix
- [ ] Refactoring
- [ ] Documentation
- [ ] Other

### Other Information

2024-06-18 05:30 UTC, toychip requested changes
종근님 작업 수고 많으셨습니다~
특히 redis를 사용하여 구현하신 것 놀랐습니다!
반환 타입, 비동기처리, oauth를 고려하지 않은 password등 의견 남겨봤는데, 확인 부탁드립니다~!

2024-06-18 05:30 UTC, toychip commented on src/main/java/com/api/ttoklip/domain/email/Repository/EmailRepository.java
> +@Repository
JpaRepository는 자체적으로 @Repository 애노테이션을 갖고 있어서 지워도 될 것 같습니다~!

2024-06-18 05:30 UTC, toychip commented on src/main/java/com/api/ttoklip/domain/email/controller/EmailController.java
> +        }
해당 내용을 Controller에서 하는 게 맞을까요?
제 생각에는 DTO 자체에서 @NotNull 혹은 @NotEmpty 를 사용하거나 검증 메서드를 Service에서 하면 좋을 것 같아요.
또한 예외처리는 저희가 Custom한 예외를 발생시키는 게 좋을 것 같네요!
또한 응답 자체를 String이 아닌 저희가 정한 API 스펙에 맞게 SuccessResponse<String> 같은 형식이 맞지 않을까 싶네요~

2024-06-18 05:30 UTC, toychip commented on src/main/java/com/api/ttoklip/domain/email/controller/EmailController.java
> +        return isVerify ? "인증이 완료되었습니다." : "인증 실패하셨습니다.";
이것도 반환 방식 바꿔야할 것 같네요!

2024-06-18 05:30 UTC, toychip commented on src/main/java/com/api/ttoklip/domain/email/entity/Email.java
> +    @Column(name = "email_id", unique = true, nullable = false)
Unique 설정 사용시 쿼리가 이상하게 사용됩니다~
쿼리를 자세히 보기 위해 로그를 찍고 실행해보면
`alter table Member 
       add constraint UK_ektea7vp6e3low620iewuxhlq unique (id)
`
이렇게 실행되므로, Table 자체에서 UniqueConstraint 를 사용해야하는게 훨씬 유용합니다.

2024-06-18 05:30 UTC, toychip commented on src/main/java/com/api/ttoklip/domain/email/entity/Email.java
> +    }
생성자는 private로 숨기고, static factory method를 사용하면 어떨까요?
```
@Builder
    private Email(String email) {
        this.email = email;
        this.emailStatus = false;
    }

public static Email from(String email){
    return new Email(email, false);
}
```
와 같이 표현 가능하겠네요!

2024-06-18 05:30 UTC, toychip commented on src/main/java/com/api/ttoklip/domain/email/service/EmailService.java
> +    private static final String senderEmail = "gmfd78459123@gmail.com";
상수라면 SENDER_EMAIL 로 표현하는 게 더 좋을 것 같네요!

2024-06-18 05:30 UTC, toychip commented on src/main/java/com/api/ttoklip/domain/email/service/EmailService.java
> +        redisUtil.setDataExpire(email, authCode, 60 * 30L);
Redis를 사용하셨군요! 
Redis를 사용하지 않아도 충분히 구현은 가능할텐데 레디스를 사용한 이유를 알 수 있을까요~?

2024-06-18 05:30 UTC, toychip commented on src/main/java/com/api/ttoklip/domain/email/service/EmailService.java
> +    }
만약 네트워크 오류나 string을 받아오는 과정이나 만약 Email 객체를 생성하다 예외가 발생하거등 예외가 발생하면 어떻게 될까요?
트랜잭션 전파가 어디까지 되고 예외가 어디까지 전파될까요?
이메일 전송할 때는 비동기로 처리해야하지 않을까요?
좋은 글 있어 첨부드립니다. 참고 부탁드려요. 
https://xxeol.tistory.com/51

2024-06-18 05:30 UTC, toychip commented on src/main/java/com/api/ttoklip/domain/member/domain/Member.java
> +    private String password;
지금 로컬 로그인만 고려하여 password 필드를 추가하신 것으로 보입니다.
저희가 클라이언트한테 oauth accessToken을 받았던 것 기억하실까요?
oauth 정보로 회원가입을 진행할 때는 password 필드 자체를 고려하지 않았으므로 oauth로 가입한 계정들은 password가 null로 들어갈 것 같아요.
oauth 도 password를 해시하여 생성하는 게 좋지 않을까요?

2024-06-18 07:00 UTC, why-only-english commented on src/main/java/com/api/ttoklip/domain/email/service/EmailService.java
> +        redisUtil.setDataExpire(email, authCode, 60 * 30L);
Redis를 사용한 이유는 다음과 같아요 ~
성능적인 면에선 인 메모리 구조로 Disk에 접근하지 않고 데이터를 바로 처리할 수 있기 때문에 이점이 있고요!
인증번호처럼 만료시간이 필요한 데이터일 경우에 Redis는 키(메일)-밸류(인증번호) 구조로 각 키에 대해 만료시간을 설정할 수 있어서 Redis를 이용해 구현해 보았습니다  ~!

2024-06-18 07:02 UTC, why-only-english commented on src/main/java/com/api/ttoklip/domain/email/controller/EmailController.java
> +        return isVerify ? "인증이 완료되었습니다." : "인증 실패하셨습니다.";
어쩐지 커밋 하기 전에 뭔가 찝찝했는데 Todo에 적어놨던걸 놓쳤네요 ~ 
수정할게요 ~!

2024-06-18 07:05 UTC, why-only-english commented on src/main/java/com/api/ttoklip/domain/email/service/EmailService.java
> +        redisUtil.setDataExpire(email, authCode, 60 * 30L);
준형님 덕분에 면접 답변 하나 얻어 갑니다 ~

2024-06-26 15:11 UTC, why-only-english commented on src/main/java/com/api/ttoklip/domain/email/service/EmailService.java
> +    private static final String senderEmail = "gmfd78459123@gmail.com";
yml 파일에서 관리할 수 있게 수정했습니다 ~!

2024-07-07 11:51 UTC, toychip approved these changes
머지 고고 고생하셨습니다.

2024-07-07 11:52 UTC, merged