pr Feat/40 newsletter delete admin
ttoklip/BackEnd pull request #194
Opened 2024-08-28 09:17 UTC by why-only-english

### Issue number and Link

- #189 

### Summary

관리자의 뉴스레터 삭제 기능 구현 

### PR Type

- [ ] Feature
- [ ] Bugfix
- [ ] Refactoring
- [ ] Documentation
- [ ] Other

2024-08-28 09:29 UTC, toychip requested changes
뉴스레터 삭제 작업 고생 많으셨습니다
삭제 부분에서 권한 확인 부분 수정 부탁드려요.
또, 여기서 뉴스레터를 조회, 오늘의 뉴스레터 선정 할 때 삭제된 것을 제외하고 갖고와야할 것 같은데 지금 그부분은 추가되지 않은 것 같습니다.

2024-08-28 09:29 UTC, toychip commented on src/main/java/com/api/ttoklip/domain/newsletter/post/service/NewsletterPostService.java
> +        newsletterCommonService.checkEditPermission(newsletter);
이건 예전이 잘못 만든 것 같아요.
관리자가 여러명 일 수 있고, 같이 관리할 수있을 것 같아요.
현재 여기서 사용하는 것은 문제 없지만 
checkEditPermission()에서 현재 사용자를 찾고, Role이 관리자가 맞는지 확인하도록 변경라면 될듯합니다.
newsletter를 안넘이는 방식으로도 수정할 수 있을 것 같습니다.

2024-08-28 09:41 UTC, why-only-english commented on src/main/java/com/api/ttoklip/domain/newsletter/post/service/NewsletterPostService.java
> +        newsletterCommonService.checkEditPermission(newsletter);
넵 확인해볼게요 ~!

2024-08-30 12:27 UTC, why-only-english commented on src/main/java/com/api/ttoklip/domain/newsletter/post/service/NewsletterPostService.java
> +        newsletterCommonService.checkEditPermission(newsletter);
```
    public void checkEditAndManagerPermission(final Newsletter newsletter) {
        Long writerId = newsletter.getMember().getId();
        Member currentMember = getCurrentMember();

        if (!writerId.equals(currentMember.getId())) {
            throw new ApiException(ErrorType.UNAUTHORIZED_EDIT_POST);
        }

        if (!currentMember.getRole().equals("MANAGER")) {
            throw new ApiException(ErrorType.UNAUTHORIZED_DELETE_POST);
        }
    }
```

이런 식으로 작성자와 현재 사용자가 동일한지, 그리고 현재 사용자가 MANAGER 권한이 있는지 확인하는 checkEditAndManagerPermission 메서드를 만들어봤는데요. 

뉴스레터 삭제 api 요청은 SecurityConfig에서 MANAGER 권한이 있는 사람만 가능하게 해놓은 상태인데 메서드에서 한 번 더 검증이 필요할까요 ~? 어떻게 생각하시는지 의견 궁금합니다 ~!

2024-08-30 14:39 UTC, toychip commented on src/main/java/com/api/ttoklip/domain/newsletter/post/service/NewsletterPostService.java
> +        newsletterCommonService.checkEditPermission(newsletter);
'''
if (!writerId.equals(currentMember.getId())) {
    throw new ApiException(ErrorType.UNAUTHORIZED_EDIT_POST);
}
'''
이 부분은 제거해도 되지 않을까요? 전에 말씀드렷다싶이 A관리자와 B관리자 모두 숮어할 수 있어야한다고 생각합니다~
그ㅐㄹ서 Newsletter를 checkEditAndManagerPermission()에 넘기지 않아도 된다고 말씀드린거였어요~

2024-08-30 16:51 UTC, why-only-english commented on src/main/java/com/api/ttoklip/domain/newsletter/post/service/NewsletterPostService.java
> +        newsletterCommonService.checkEditPermission(newsletter);
아하 "작성자가 달라도 관리자면 삭제할 수 있게 하도록" 이해했습니다~  👍👍

2024-09-01 05:20 UTC, toychip requested changes
이제 뉴스레터 중에서 TodayNewsLetter 를 발급할 때나 다른 뉴스레터를 Get요청할 때 isDeleted 필드로 확인해야할 것 같습니다~ 
softDeleted 처리했는데 보이면 안되니까요!

2024-09-02 03:29 UTC, toychip approved these changes
오늘의 뉴스레터 뽑는 스케줄러에서 제외되도록 제가 수정했습니다~
참고해보십쇼
- #200

2024-09-02 03:30 UTC, merged