Fix/27 newsletter main activated
ttoklip/BackEnd pull request #202
Opened 2024-09-03 12:23 UTC by why-only-english

### Issue number and Link

- #201 

### Summary

뉴스레터 메인화면 삭제 게시글 처리
리팩토링

### PR Type

- [ ] Feature
- [ ] Bugfix
- [ ] Refactoring
- [ ] Documentation
- [ ] Other

2024-09-03 13:08 UTC, toychip requested changes
랜덤 4개 갖고오는 쿼리가 누락됟 것 같네요!
추가 부탁드립니다.

2024-09-03 13:08 UTC, toychip commented on src/main/java/com/api/ttoklip/domain/newsletter/post/repository/NewsletterQueryDslRepositoryImpl.java
>      }
이부분 랜덤 4개 갖고오는 쿼리를 제거하셔서 오류날 것 같네요.!
저번 제가 수정한 Pr부분 보시면 좋을 듯 합니다~
추가 부탁드립니다!
https://github.com/ttoklip/BackEnd/pull/200/files#diff-03bd29ba2ad6044e7fd6251afafc5a91fa1607257d4685043c8a7dc54ee18aacR147

```java

    @Override
    public List<Newsletter> findRandom4ActiveNewsletters() {
        long count = getNewsletterCount();

        // 전체 개수 내에서 랜덤한 인덱스 생성
        // 랜덤 인덱스의 최대값을 조정하여 초과하지 않도록 설정
        // 최소값을 0으로 설정하여 인덱스가 음수가 되지 않도록 함
        int maxIndex = (int) Math.max(0, count - 4);
        int randomIndex = new Random().nextInt(maxIndex + 1);

        // 랜덤한 인덱스에서 시작하여 4개의 결과 가져오기
        return jpaQueryFactory.selectFrom(newsletter)
                .where(
                        newsletter.deleted.isFalse()
                )
                .offset(randomIndex)
                .limit(4)
                .fetch();
    }

    private long getNewsletterCount() {
        Long count = jpaQueryFactory.select(Wildcard.count)
                .from(newsletter)
                .where(newsletter.deleted.isFalse())
                .fetchOne();

        if (count == null) {
            return 0;
        }

        return count;
    }
```

2024-09-04 11:09 UTC, why-only-english commented on src/main/java/com/api/ttoklip/domain/newsletter/post/repository/NewsletterQueryDslRepositoryImpl.java
>      }
아하 누락이 있었네네요 ㅠ 확인했어요 ~!

2024-09-04 15:36 UTC, toychip commented on src/main/java/com/api/ttoklip/domain/newsletter/post/repository/NewsletterRepository.java
> +@Primary
요건 뭘까요..?
필요 없어보입니다

2024-09-04 22:59 UTC, why-only-english commented on src/main/java/com/api/ttoklip/domain/newsletter/post/repository/NewsletterRepository.java
> +@Primary
```
Description:

Parameter 0 of constructor in com.api.ttoklip.domain.newsletter.main.service.NewsletterMainService required a single bean, but 2 were found:
	- newsletterQueryDslRepositoryImpl: defined in file [D:\ttoklip-backend\BackEnd\out\production\classes\com\api\ttoklip\domain\newsletter\post\repository\NewsletterQueryDslRepositoryImpl.class]
	- newsletterRepository: defined in com.api.ttoklip.domain.newsletter.post.repository.NewsletterRepository defined in @EnableJpaRepositories declared on JpaRepositoriesRegistrar.EnableJpaRepositoriesConfiguration


Action:

Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed
```

위 오류 있어서 해결하려고 추가했어요 !

2024-09-05 11:56 UTC, why-only-english commented on src/main/java/com/api/ttoklip/domain/newsletter/post/repository/NewsletterRepository.java
> +@Primary
아하 그렇네요! 
```
NewsletterQueryDslRepositoryImpl: QueryDSL 기능을 구현한 실제 구현체
NewsletterRepository: Spring이 자동으로 생성한 구현체인데, 이 구현체는 NewsletterQueryDslRepository도 상속받고 있으므로 이를 구현하는 것으로 간주됨
```
이 부분을 생각 못했는데 상세한 설명 감사합니다 NewsletterRepository만 주입하는 걸로 수정했습니다 !!

2024-09-05 12:47 UTC, toychip approved these changes
굿굿~ 고생 많으셨어요

2024-09-05 12:47 UTC, merged