pr Feat/42 search cart
ttoklip/BackEnd pull request #223
Opened 2024-09-26 07:36 UTC by why-only-english

### Issue number and Link

이슈 번호

- #220 

### Summary

함께해요 제목 + 내용 검색 추가하였습니다.

### PR Type

- [x] Feature
- [ ] Bugfix
- [ ] Refactoring
- [x] Documentation
- [ ] Other

2024-09-26 07:37 UTC, why-only-english reviewed
@toychip 지금 함께해요 이외에 다른 도메인들은 제목 검색만 돼서 PM님께 물어보고 다른 도메인도 제목 + 내용 검색으로 수정하면 될 것 같아요 ~~

2024-09-26 14:20 UTC, toychip requested changes
검색 작업 고생하셨습니다~
다만 N + 1 쿼리가 발생할 수 있을 것 같은데, 필요한 cart.getMembers()를 단일쿼리로 먼저 조회한 후에 이를 사용하는 방식으로 해야할 것 같아요.

2024-09-26 14:31 UTC, toychip commented on src/main/java/com/api/ttoklip/domain/mypage/dto/response/UserCartSingleResponse.java
> +                .commentCount(cart.getCartComments().size())
요것도 N + 1 일어나지 않을까요~

2024-09-26 14:32 UTC, toychip commented on src/main/java/com/api/ttoklip/domain/mypage/dto/response/UserCartSingleResponse.java
> +                .writerProfileImageUrl(cart.getMember().getProfile().getProfileImgUrl())
요것도 N + 1 일어나지 않을까요~

2024-09-26 14:32 UTC, toychip commented on src/main/java/com/api/ttoklip/domain/mypage/dto/response/UserCartSingleResponse.java
> +                .partyCnt(cart.getCartMembers().size())
요것도 N + 1 일어나지 않을까요~

2024-09-26 14:36 UTC, toychip approved these changes

2024-09-26 23:04 UTC, why-only-english commented on src/main/java/com/api/ttoklip/domain/search/response/CartSingleResponse.java
> +    }
넵 반영했습니다 ~!

https://github.com/ttoklip/BackEnd/pull/223/commits/683b59efe08c3c786284bf78ce881defcceaa8e2

2024-09-28 14:42 UTC, toychip approved these changes

2024-09-29 14:48 UTC, merged