pr docs: 명세서 가독성 개선
ttoklip/BackEnd pull request #290
Opened 2024-11-19 12:35 UTC by why-only-english

### Issue number and Link

- #269 

### Summary
ControllerDocs 인터페이스를 활용하여 Controller 구현체의 가독성을 개선합니다.

### Other Information

2024-11-20 13:06 UTC, toychip requested changes
고생하셨습니다~
Http method 종류랑 value는 원복 부탁드립니다.
api 명세서 스펙은 보여야할 것 같아요.

2024-11-20 13:06 UTC, toychip commented on ttoklip-api/src/main/java/com/api/auth/local/presentation/LocalAuthController.java
>          return new TtoklipResponse<>(authFacade.signup(request));
명세서 관련 코드를 interface로 분리 부탁드린거였습니다!
Http method 종류랑 value, consumes는 보여야할 것 같아요~

2024-11-25 19:50 UTC, toychip requested changes
종근님 명세서 작업 너무 고생 많으셨습니다~
검색 API 충돌만 해결해주시면 바로 머지해도 될 것 같습니다!

2024-11-26 00:41 UTC, why-only-english commented
> 종근님 명세서 작업 너무 고생 많으셨습니다~ 검색 API 충돌만 해결해주시면 바로 머지해도 될 것 같습니다!

2024-11-26 00:41 UTC, why-only-english commented
> 종근님 명세서 작업 너무 고생 많으셨습니다~ 검색 API 충돌만 해결해주시면 바로 머지해도 될 것 같습니다!

2024-11-26 00:42 UTC, why-only-english commented
> 종근님 명세서 작업 너무 고생 많으셨습니다~ 검색 API 충돌만 해결해주시면 바로 머지해도 될 것 같습니다!

충돌 해결했슴니다 어프로브 부탁드립니두

2024-11-26 03:40 UTC, toychip approved these changes
굿굿 고생하셨습니다~

2024-11-26 05:50 UTC, merged