pr Docs/4 mypage swagger
ttoklip/BackEnd pull request #40
Opened 2024-02-06 06:43 UTC by psae0714

### Issue number and Link
이슈 번호 : #32

### Summary
마이페이지 api들을 구현하였고, 그중 공지사항과 이용약관 crud 기능구현을 하였습니다 공지사항 삭제는 소프트 삭제가 구현되어있습니다

### PR Type
- [X] Feature
- [ ] Bugfix
- [ ] Refactoring
- [X] Documentation
- [ ] Other

### Other Information
후에 ~api 연결 필요
로그인 기능이 완료되면 관련 기능들 구현 완료 예정입니다
공지사항과 이용약관은 관리자 페이지 기능과 연관이 있어 후에 리펙토링 예정입니다
고객센터 기능중 문의하기를 제외한 자주 나오는 질문은 로그인과 관련이 없지만 로그인이 완료된 후 같이 구현하도록 하겠습니다

### Common Type

~~~
- feat : 새로운 기능 구현
- add : feat 이외의 부수적인 코드, 파일, 라이브러리 추가
- chore : 패키지 구조, 함수 및 변수명 변경 등의 작은 작업
- fix : 버그 및 오류 해결
- del : 불필요한 코드, 파일, 주석 삭제
- docs : 명세서 작성
- refactor : 코드 리팩토링
- merge : 서로 다른 브랜치 간의 코드 병합
- setting : 프로젝트 기초 세팅 관련 작업
~~~
### branch

~~~
Feature/{이슈 번호 x, feat 순서}-{작업 내용}

ex)
Feature/3-home-api
Feature/4-home-crud
~~~

2024-02-06 13:41 UTC, why-only-english reviewed
마이페이지 부분에서 공지사항, 이용약관 구현하느라 고생하셨습니다! 리뷰 남길게요 👍

2024-02-06 13:43 UTC, why-only-english commented on src/main/java/com/api/ttoklip/domain/mypage/main/controller/MyPageController.java
가독성을 위해 api 별로 개행문자가 있으면 좋을 것 같아요 :)

2024-02-06 13:46 UTC, why-only-english commented on src/main/java/com/api/ttoklip/domain/mypage/main/dto/response/ScrapPostResponse.java
> +    private int countComments;
JPA에서 null 타입을 사용하기 위해 `int `보단 래퍼 클래스인 `Long`을 사용하는게 좋다고 합니다 !
참고자료 첨부할게요 [참고자료](https://koopi.tistory.com/52)

2024-02-07 02:46 UTC, psae0714 commented on src/main/java/com/api/ttoklip/domain/mypage/main/dto/response/ScrapPostResponse.java
> +    private int countComments;
넵! 수정하겠습니다

2024-02-07 02:47 UTC, psae0714 commented on src/main/java/com/api/ttoklip/domain/mypage/main/controller/MyPageController.java
넵 수정하겠습니다

2024-02-07 05:30 UTC, LEEJaeHyeok97 commented
전반적으로 잘 만드신것 같습니다. 다른 핵심적 기능에서도 활약 부탁합니다!

2024-02-08 00:21 UTC, toychip requested changes
알람 설정, 마이페이지, 공지 사항, 이용 약관 확인했습니다.
다만 기본적인 파라미터 사용법에서 잘못된 부분에 대해 달아봤습니다.
확인해주시고 반영해주시면 좋겠습니다!

2024-02-08 00:21 UTC, toychip commented on src/main/java/com/api/ttoklip/domain/mypage/noti/post/controller/NotiController.java
> +    public SuccessResponse<List<Notice>> getNoticeList() {
엔티티를 직접 반환하는 <List<Notice>>를 반환하는 것이 아닌, NoticeSingleResponse라는 응답 dto를 만들고 페이징처리 관련과 함께 녹여야합니다.
JPA를 사용할 때 절대 엔티티 자체를 반환해서는 안됩니다.
검색 기능 pull request에서 반환하는 방식을 참고하시면 좋을 것 같네요.

또한 지금 상태에서 데이터가 100만개 있다고 가정했을 때 지금은 100만개를 그대로 갖고오지 않을까요?
페이징 처리가 필요합니다.

2024-02-08 00:21 UTC, toychip commented on src/main/java/com/api/ttoklip/domain/mypage/noti/post/controller/NotiController.java
> +    @PostMapping(value = "/create", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
저희가 @ModelAttribute로 생성을 했던 이유는 사진, 파일 등 MultipartFile을 해결하기 위해서였습니다.
사진이 포함되어있지 않고 json으로 된 객체를 생성할 때는 @RequestBody를 사용하는 것이 적절합니다.

2024-02-08 00:21 UTC, toychip commented on src/main/java/com/api/ttoklip/domain/mypage/noti/post/service/NotiService.java
> +        return notice.getId();
저희가 엔티티 id만을 반환하는 것이 아닌 Message 객체를 사용하여 몇번째의 어떠한 것이 생성되었는지 응답했던 것 기억하실까요?

2024-02-08 00:21 UTC, toychip commented on src/main/java/com/api/ttoklip/domain/mypage/noti/post/controller/NotiController.java
> +        return new SuccessResponse<>(response);
네 이렇게 게시글의 몇번째를 조회할 때 `@PathVariable`을 사용합니다. 올바른 사용이네요. 👍

2024-02-08 00:21 UTC, toychip commented on src/main/java/com/api/ttoklip/domain/mypage/noti/post/service/NotiService.java
> +        Notice notice = findNoticeById(noticeId);
지금 과연 soft delete를 그대로 구현한 것 맞을까요? 
지금은 무한 삭제가 될 것 같습니다.
이유는, findNoticeById(noticeId) 메서드는 DB에 존재하는지만 확인하지, 비활성화이면서 존재하는 것을 갖고오지 않기 때문입니다.
삭제 요청을 하면 삭제 요청은 되겠지만 실제로 갖고오는 findNoticeById() 메서드는 삭제된 것도 갖고오게 되겠네요.

2024-02-08 00:21 UTC, toychip commented on src/main/java/com/api/ttoklip/domain/mypage/noti/post/service/NotiService.java
> +    public Notice findNoticeById(final Long noticeId){
soft delete로 삭제되는 것은 올바르게 잘 구현하셨는데, 정작 데이터를 갖고 올 때는 삭제된 것인지 확인하지 않고 있습니다.

2024-02-08 00:21 UTC, toychip commented on src/main/java/com/api/ttoklip/domain/mypage/noti/post/service/NotiService.java
> +    public Message edit(final Long noticeId, final NoticeCreateRequest request) {
지금 수정하는 곳에서 NoticeCreateRequest를 사용하고 있네요. 
생성과 수정하는 곳 모두에서 사용된다면 NoticeRequest아닐까요?
하지만 그 전에, 저희는 Editor를 사용하여 특정한 객체를 넘기기 때문에 사용하는 필드가 같더라도 NoticeEditRequest가 필요할 것 같습니다.

2024-02-08 00:21 UTC, toychip commented on src/main/java/com/api/ttoklip/domain/mypage/term/controller/TermController.java
> +    public SuccessResponse<List<Term>> getTermList() {
이것도,, 절대 엔티티 자체를 반환해서는 안됩니다.
페이징처리를 진행한 응답 DTO로 반환해야합니다.

2024-02-08 00:21 UTC, toychip commented on src/main/java/com/api/ttoklip/domain/mypage/term/service/TermService.java
> +    /* -------------------------------------------- COMMON -------------------------------------------- */
공지사항은 삭제되는 로직이 없기 떄문에 softDelete가 존재할 필요가 없고, 아래와 같이 해도 정상 작동합니다.

2024-02-08 00:21 UTC, toychip commented on src/main/java/com/api/ttoklip/domain/mypage/term/service/TermService.java
> +        return term.getId();
저희가 만든 Message 객체 사용해주세요.

2024-02-08 00:21 UTC, toychip commented on src/main/java/com/api/ttoklip/domain/mypage/term/dto/response/TermResponse.java
> +        }
과연 하나가 null일 수 있을까요? 
Service에서 findTermById로 찾아오고 그곳에서 없다면 올바른 커스텀 에러를 터뜨려주셨습니다.
```
termRepository.findById(termId)
                .orElseThrow(()->new ApiException(ErrorType.TERM_NOT_FOUND));
```
이렇게 올바르게 사용했기 때문에 of 메서드에 들어오는 Term이 절대 null일 수 없습니다.
만약 이 상황에 Term엔티티가 다른 엔티티와 Term(1) : Other(n) 매핑을 하고 있고 Lazy로 매핑이 되어있으며 fetch join하지 않고 proxy 객체로 갖고오는 상황에서 List에 접근했을 때 오류가 나는 것입니다.
이곳에서는 List<> 로 갖는 필드 자체가 없으므로 위 검증 로직은 필요 없을 것 같네요.

2024-02-10 14:51 UTC, toychip requested changes
세준님 수정 반영하신것 확인했습니다.
객체를 바인딩할때 @ModelAttribute와 @RequestBody의 차이와, post, patch 메서드에서 사용시 어떻게 값을 바인딩할지 좀 더 알아보시고 사용하시면 더 좋을 것 같아요!

2024-02-10 14:51 UTC, toychip commented on src/main/java/com/api/ttoklip/domain/mypage/main/controller/MyPageController.java
> +    @DeleteMapping("/unblock/{targetId}")
string으로는 PathVariable로 받는것을 권장하지 않습니다.
PathVariable와 RequestParam 사용법의 차이를 좀 더 알아보시면 좋을 것 같아요.

2024-02-10 14:51 UTC, toychip commented on src/main/java/com/api/ttoklip/domain/mypage/main/dto/request/BlockedRequest.java
> +public class BlockedRequest {
예전에 Request객체가 필드가 1개일 경우 json 역직렬화 오류를 해결하기 위해 남겼던 리뷰 기억하실까요? [리뷰](https://github.com/ttoklip/BackEnd/pulls?q=is%3Apr+is%3Aclosed#discussion_r1466060807)
또한 생성자가 존재하지 않을 경우 서비스단계에서 꺼내올 수가 없으므로 @AllArgsConstructor가 있어야할 것 같네요.

2024-02-10 14:51 UTC, toychip commented on src/main/java/com/api/ttoklip/domain/mypage/main/dto/response/RestricetdResponse.java
> +    @Schema(description = "제ㅔ제기간")
오타 있습니다!

2024-02-10 14:51 UTC, toychip commented on src/main/java/com/api/ttoklip/domain/mypage/noti/post/controller/NoticeController.java
> +    public SuccessResponse<Message> register(final @Validated @ModelAttribute NoticeCreateRequest request) {
json만으로 객체를 생성할 경우 Form Data로 생성할 필요가 없지 않을까요?
지금까지 @ModelAttribute로 객체를 생성했던 이유는 사진을 처리하기 위해, MultiPartFile을 해결하기 위해서였습니다.
이렇게 json만으로 생성할 경우 @RequestBody로 생성하시면 될 것 같습니다.

2024-02-10 14:51 UTC, toychip commented on src/main/java/com/api/ttoklip/domain/mypage/noti/post/controller/NoticeController.java
> +    public SuccessResponse<Message> edit (final @PathVariable Long noticeId, final NoticeEditRequest request) {
Patch 메서드에서 json으로 된 NoticeEditRequest 객체를 받고싶어하시는 것을 알겠는데 값을 바인딩하는 방법이 나와있지 않네요.
json으로된 값으로 받아오려면 @RequestBody를 써야합니다.

2024-02-10 14:51 UTC, toychip commented on src/main/java/com/api/ttoklip/domain/mypage/noti/post/domain/Notice.java
> +        super.deactivate();// Notice 엔티티 비활성화
다른곳에서 해당 메서드를 Override해서 사용한 이유는 본인과 연관된 엔티티까지 비활성화하기 위해서였습니다.
예를 들어 게시판을 비활성화(soft delete) 할 때 게시판의 image, 댓글 또한 비활성화를 하기 위해 사용되었습니다.
하지만 지금은 다른곳을 함께 비활성화한다기 보다 본인것만 비활성화한다면 오버라이드하는 의미가 있을까요?

2024-02-10 14:51 UTC, toychip commented on src/main/java/com/api/ttoklip/domain/mypage/noti/post/domain/NoticeRepository.java
> +    Page<Notice> findByContentContaining (final Pageable pageable);
NoticePagingRepository에서 countQuery 메서드가 이미 카운트 쿼리를 사용한 것 아닐까요? 
제가 카운트 쿼리와 실제 데이터를 나눈 이유는 이 둘을 조합해서 결국 PageImpl 객체로 반환하기 위해서입니다.
queryDSL로 사용한 두 메서드를 서비스에서 조합하시고 해당 메서드는 지우셔도 됩니다.

2024-02-10 14:51 UTC, toychip commented on src/main/java/com/api/ttoklip/domain/mypage/noti/post/service/NoticeService.java
> +public class NoticeService {
다 좋은데 커밋 전에 포멧팅 단축키를 한 번 사용하고 올려주시면 좋겠습니다.
윈도우 기준으로 Ctrl + Alt + L 단축키를 누르면 코드가 정리되므로 보기 깔끔해집니다.

2024-02-10 14:51 UTC, toychip commented on src/main/java/com/api/ttoklip/domain/mypage/term/controller/TermController.java
> +    public SuccessResponse<Message> register(final @Valid @ModelAttribute TermCreateRequest request) {
이부분도 위와 같네요. form-data로 받아야할까요?

2024-02-10 14:51 UTC, toychip commented on src/main/java/com/api/ttoklip/domain/mypage/term/controller/TermController.java
> +    public SuccessResponse<Message> edit (final @PathVariable Long termId, final TermEditRequest request) {
이부분도 위와 같네요. 객체를 어떻게 바인딩해야할까요?

2024-02-10 14:56 UTC, why-only-english commented on src/main/java/com/api/ttoklip/domain/mypage/noti/post/service/NoticeService.java
> +public class NoticeService {
코드 정리할 때 한 줄씩 Ctrl + Shift + Enter 했었는데 꿀팁 감사합니다 ..

2024-02-10 15:04 UTC, why-only-english commented on src/main/java/com/api/ttoklip/domain/mypage/term/service/TermService.java
> +        return Message.registerPostSuccess(Term.class,termId);
TermConstant에서 예시 응답 만드신 대로 응답받으려면 Message에서 메서드(`registerTermSuccess` 이런식으로) 추가하면 좋을 것 같아요!

2024-02-10 15:05 UTC, why-only-english commented on src/main/java/com/api/ttoklip/domain/mypage/term/service/TermService.java
> +        return Message.editPostSuccess(Term.class, term.getId());
여기도 위와 같습니다!!

2024-02-10 15:07 UTC, why-only-english approved these changes
세준님 수정 작업 고생하셨습니다~ 리뷰 남겨놓을게요

2024-02-10 15:08 UTC, why-only-english commented on src/main/java/com/api/ttoklip/domain/mypage/term/service/TermService.java
> +        return Message.registerPostSuccess(Term.class,termId);
TermConstant에서 예시 응답 만드신 대로 응답받으려면 Message에서 메서드(registerTermSuccess 이런식으로) 추가하면 좋을 것 같아요!

2024-02-10 15:08 UTC, why-only-english commented on src/main/java/com/api/ttoklip/domain/mypage/term/service/TermService.java
> +        return Message.editPostSuccess(Term.class, term.getId());
여기도 위와 같습니다!!

2024-02-12 12:09 UTC, why-only-english approved these changes
세준님
중복 쿼리문 삭제, 오타 수정, 코드 정렬 확인했습니다!

2024-02-13 04:00 UTC, toychip approved these changes
세준님 수고하셨습니다! 해당 pr 마지막 리뷰가 될 것 같네요!

2024-02-13 15:15 UTC, merged

2024-02-13 15:15 UTC, toychip approved these changes
고생많으셨습니다. 머지부탁드려요!

2024-02-13 17:30 UTC, why-only-english commented
고생 많으셨습니다 !